#!/bin/bash

# Function to get DNS information for a subdomain
get_dns_info() {
    subdomain=$1
    domain=$2
    dig_result=$(dig "$subdomain.$domain" +short)
    record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/ {print $4}')
    echo "The subdomain $subdomain is a $record_type record and points to $dig_result"
}

# Main function
main() {
    domain=$1

    # If subdomain is provided, get info for that subdomain
    if [ -n "$2" ]; then
        subdomain=$2
        get_dns_info "$subdomain" "$domain"
    else
        # Otherwise, get info for default subdomains
        subdomains=("www" "lb-01" "web-01" "web-02")
        for subdomain in "${subdomains[@]}"; do
            get_dns_info "$subdomain" "$domain"
        done
    fi
}

# Check if domain argument is provided
if [ -z "$1" ]; then
    echo "Error: Domain argument is missing"
    exit 1
fi

# Call the main function
main "$@"

