#!/usr/bin/env bash
# Script: domain_info.sh
# Description: Displays information about subdomains

# Function to retrieve and display domain information
domain_info () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

# Check the number of arguments provided
if [ "$#" == 1 ]; then
    # Query default subdomains
    domain_info "$1" "www"
    domain_info "$1" "lb-01"
    domain_info "$1" "web-01"
    domain_info "$1" "web-02"
elif [ "$#" == 2 ]; then
    # Query specific subdomain
    domain_info "$1" "$2"
fi

