#!/usr/bin/env bash

# This script transfers a file from a client to a server.
# It accepts 4 parameters:
#   - The path to the file to be transferred
#   - The IP of the server to transfer the file to
#   - The username used for the SCP connection
#   - The path to the SSH private key used by SCP

# Display usage if less than 4 parameters are passed
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    # Transfer the file to the user's home directory on the server using SCP
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi

