#!/usr/bin/env bash
# Configure Nginx with custom HTTP response header

# Update Packages before performing installations
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create a custom 404 error page
echo "This is a custom 404 error page." | sudo tee /var/www/html/404.html

# Configure Nginx to include custom header
header_config="add_header X-Served-By \$hostname;"
sudo sed -i "/server_name _/a $header_config" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart

