#!/usr/bin/env bash

# Question, #1 What is a MAC address? Answer, #1 The unique identifier of a network interface

2

# Question, #2 What is an IP address? Answer, #2 Is to devices connected to a network what postal address is to houses and Is a number that network devices use to connect to networks 

1
3
