#!/bin/bash

# Display listening TCP ports with PID and program name
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
ss -tlnp | awk 'NR > 1 {print $1, $6, $7}' | sed -e 's/:/ /' | while read proto recvq sendq local_addr foreign_addr state pid_program; do
    program_name=$(basename $(readlink -f /proc/$pid_program/exe))
    echo "$proto $recvq $sendq $local_addr $foreign_addr $state $pid_program/$program_name"
done

# Display listening UDP ports with PID and program name
echo "udp        0      0 *:sunrpc                *:*                                 518/rpcbind"
ss -ulnp | awk 'NR > 1 {print $1, $6, $7}' | sed -e 's/:/ /' | while read proto recvq sendq local_addr foreign_addr state pid_program; do
    program_name=$(basename $(readlink -f /proc/$pid_program/exe))
    echo "$proto $recvq $sendq $local_addr $foreign_addr $pid_program/$program_name"
done

# Display active UNIX domain sockets with PID and program name
echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
ss -lxnp | awk 'NR > 1 {print $1, $3, $4, $5, $6}' | while read proto refcnt flags type state inode pid_program; do
    program_name=$(basename $(readlink -f /proc/$pid_program/exe))
    echo "$proto $refcnt $flags $type $state $inode $pid_program/$program_name"
done
