#!/usr/bin/env bash
# Displays "Best School" 10 times, with "Hi" on the 10th iteration.

for (( COUNTER = 1; COUNTER <= 10; COUNTER++ )); do
    if [ $COUNTER -eq 10 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi
done

