#!/usr/bin/env bash
# Displays "Best School" 10 times with special messages on the 4th and 8th iterations.

for (( COUNTER = 1; COUNTER <= 10; COUNTER++ )); do
    if [ $COUNTER -eq 4 ]; then
        echo "bad luck"
    elif [ $COUNTER -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
done

