#!/usr/bin/env bash
# This script connects to the server using SSH with a private key.

# Define variables
private_key="~/.ssh/school"
user="ubuntu"
server_address="54.157.164.80"

# Use ssh with private key and specified user
ssh -i ~/.ssh/school ubuntu@54.157.164.80

